name: Build and Deploy Java Application to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deploy when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      # Step 2: Set up Java environment (JDK 11 in this case)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Build the Java application using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Builds the project and skips tests (remove -DskipTests to run tests)

      # Step 4: Upload the JAR artifact (packaged in the 'target' directory)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@latest
        with:
          name: java-app
          path: target/*.jar  # Path to the packaged JAR file

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: java-app  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish Profile secret
          package: target/*.jar  # Path to the JAR file (previously uploaded)
