name: Build, Test, and Deploy Java App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies (if using Maven)
        run: |
          mvn clean install  # Packages your app as a JAR

      - name: Run application (optional)
        run: |
          cd target
          java -jar your-application.jar  # Run the JAR file for testing (optional)

      # Upload the packaged JAR/WAR file
      - name: Upload the JAR file
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: target/your-application.jar  # Make sure to adjust this path

  # Job 2: Deploy to Azure Web App
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download the JAR file
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts
          path: target/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: java-app  # Replace with your actual app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/your-application.jar  # Path to the JAR file
