name: Build, Test, and Deploy Java Application to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deploy when code is pushed to the 'main' branch

jobs:
  # Job 1: Build and Test the Java application
  build-and-test:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      # Step 2: Set up Java environment (JDK 11 in this case)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Build and Test the Java application using Maven
      - name: Build and Test with Maven
        run: mvn clean install  # Builds and runs tests

  # Job 2: Deploy to Azure Web App
  deploy:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner
    needs: build-and-test  # This job will only run after the 'build-and-test' job is successful

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      # Step 2: Set up Java environment (JDK 11 in this case)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Build the Java application (without running tests)
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Builds the project, skipping tests

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: java-app  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish Profile secret
          package: target/*.jar  # Path to the JAR file (after the build step)
