name: Build, Test, and Deploy Java App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          mkdir -p bin
          cd src
          javac Main.java -d ../bin/

      - name: Run application
        run: |
          cd bin
          java Main

      # Upload the compiled Java artifacts (bin directory)
      - name: Upload compiled Java artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: bin/

  # Job 2: Deploy to Azure Web App
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure this job runs after the build-and-test job

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download compiled Java artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts
          path: bin/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: java-app  # Replace with your actual Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: bin/  # Adjust this path if deploying a JAR or WAR file
